package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.Carreira;
import org.acme.model.DTO.CarreiraDTO;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class CarreiraRepository {
    /*
        CREATE TABLE T_RHSTU_CARREIRA(
        id_carreira NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome_carreira VARCHAR(80),
        anos_formacao NUMBER
        area_de_trabalho VARCHAR(120),
        informacao_trabalho VARCHAR(100),
        dica_treino VARCHAR(100)
        )
    */
    @Inject
    DataSource dataSource;

    public void  inserirCarreira(CarreiraDTO c) throws SQLException{
        String sql="INSERT INTO T_RHSTU_CARREIRA (nome_carreira, anos_formacao, area_de_trabalho, informacao_trabalho, dica_treino) VALUES (?, ?, ?, ?, ?)";
        try (Connection con= dataSource.getConnection();
             PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setString(1,c.getNome_carreira());
            ps.setInt(2,c.getAno_formacao());
            ps.setString(3,c.getArea_de_trabalho());
            ps.setString(4,c.getInformacao_trabalho());
            ps.setString(5,c.getDica_treino());

            ps.executeUpdate();
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    public List<Carreira> RelatorioCarreira(int id, String nome) throws SQLException{
        String sql= "SELECT * FROM T_RHSTU_CARREIRA id_carreira=? AND nome_carreira=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1,id);
            ps.setString(2,nome);

            List<Carreira> l= new ArrayList<>();
            try(ResultSet rs=ps.executeQuery()){
                while(rs.next()){
                    Carreira carreira= new Carreira();
                    carreira.setId_carreira(rs.getInt(1));
                    carreira.setNome_carreira(rs.getString(2));
                    carreira.setAno_formacao(rs.getInt(3));
                    carreira.setArea_de_trabalho(rs.getString(4));
                    carreira.setInformacao_trabalho(rs.getString(5));
                    carreira.setDica_treino(rs.getString(6));

                    l.add(carreira);
                }
                return l;
            }catch (SQLException e){
                throw new RuntimeException(e);
            }
        }
    }
    public List<Carreira> lista() throws SQLException{
        String sql="SELECT * FROM T_RHSTU_CARREIRA ORDER BY id_carreira";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {
            ResultSet rs=ps.executeQuery();
            List<Carreira>listaCarreira= new ArrayList<>();

            while (rs.next()){
                Carreira carreira= new Carreira();
                carreira.setId_carreira(rs.getInt(1));
                carreira.setNome_carreira(rs.getString(2));
                carreira.setAno_formacao(rs.getInt(3));
                carreira.setArea_de_trabalho(rs.getString(4));
                carreira.setInformacao_trabalho(rs.getString(5));
                carreira.setDica_treino(rs.getString(6));

                listaCarreira.add(carreira);
            }
            return listaCarreira;
        }
    }
    public void RemoverCadeira(int id, String carreira) throws SQLException{
        String sql= "DELETE FROM T_RHSTU_CARREIRA WHERE id_carreira=? AND nome_carreira=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setInt(1,id);
            ps.setString(2,carreira);

            int deleta=ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Foi deletado");
            }
        }catch (SQLException e) {
            throw new RuntimeException("Erro de remover");
        }
    }

    public void updanteCarreira(int id, String n, int ano, String area, String in, String di){
        String sql="UPDATE T_RHSTU_CARREIRA SET nome_carreira=?, anos_formacao=?, area_de_trabalho=?, informacao_trabalho=?, dica_treino=? WHERE id_carreira=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setString(1,n);
            ps.setInt(2,ano);
            ps.setString(3,area);
            ps.setString(4,in);
            ps.setString(5,di);
            ps.setInt(6,id);
        }catch (SQLException e){
            throw new RuntimeException("Erro de executar updante.");
        }
    }
}
