package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.Cursos;
import org.acme.model.DTO.CursosDTO;
import org.acme.service.CursosService;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class CursosRepository {
    /*CREATE TABLE T_RHSTU_CURSOS(
    id_curso INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nm_curso VARCHAR(60) NOT NULL,
    url_curso VARCHAR(200) NOT NULL,
    gratuito CHAR(2)check(gratuito='s' OR gratuito='n') not null,
    duracao NUMBER NOT NULL,
    id_carreira INTEGER NOT NULL,
    CONSTRAINT FK_T_RHSTU_CARREIRA FOREIGN KEY(id_carreira) REFERENCES T_RHSTU_CARREIRA(id_carreira)
);

*/
    @Inject
    DataSource dataSource;

    public void inserirCursos(CursosDTO cursosDTO){
        String sql= "INSERT INTO T_RHSTU_CURSOS " +
                "(nm_curso, url_curso, gratuito, duracao, id_carreira)" +
                " VALUES (?, ?, ?, ?, ?)";
        try(Connection con = dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)){

            ps.setString(1,cursosDTO.getNm_curso());
            ps.setString(2,cursosDTO.getUrl_curso());
            ps.setString(3,cursosDTO.getGratuito());
            ps.setInt(4,cursosDTO.getDuracao());
            ps.setInt(5,cursosDTO.getId_carreira());

            ps.executeUpdate();
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }

    public List<Cursos> RelatorioCursos(String nome){
        String sql="SELECT " +
                "c.id_curso, " +
                "c.nm_curso, " +
                "c.url_curso, " +
                "c.gratuito, " +
                "c.duracao," +
                " ca.id_carreira, " +
                " ca.nm_carreira "+
                " FROM T_RHSTU_CURSOS c, T_RHSTU_CARREIRA ca " +
                " WHERE ca.id_carreira= c.id_carreira AND c.nm_curso=?";
        List<Cursos> l= new ArrayList<>();
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setString(1,nome);

            try(ResultSet rs = ps.executeQuery()){
                Cursos cursos = new Cursos();
                cursos.setId_curso(rs.getInt(1));
                cursos.setUrl_curso(rs.getString(2));
                cursos.setGratuito(rs.getString(3));
                cursos.setDuracao(rs.getInt(4));
                cursos.setId_carreira(rs.getInt(5));
                cursos.setNm_carreira(rs.getString(6));

                l.add(cursos);
            }
            return l;

        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }
    public void RemoverCurso(String nomeCurso) throws SQLException{
        String sql= "DELETE FROM T_RHSTU_CURSOS WHERE nm_curso=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setString(1,nomeCurso);

            int d= ps.executeUpdate();
            if (d>0){
                throw new RuntimeException("Foi deletado");
            }

        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    public void updanteCursos(int id_curso, String nm_curso, String url_curso, String gratuito, int duracao, int id_carreira) throws  SQLException{
        String sql="UPDATE T_RHSTU_CURSOS" +
                " SET nm_curso=?, url_curso=?, gratuito=?," +
                " duracao=?, id_carreira=? WHERE id_curso=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setString(1,nm_curso);
            ps.setString(2,url_curso);
            ps.setString(3,gratuito);
            ps.setInt(4,duracao);
            ps.setInt(5,id_carreira);
            ps.setInt(6,id_curso);

            int alteracao=ps.executeUpdate();
            if (alteracao==0){
                throw new RuntimeException("Nao foi encontrado a alteracao");
            }
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }


}
