package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.Habilidade_profissionalDTO;
import org.acme.model.DTO.Usuario_habilidadeDTO;
import org.acme.model.Habilidade_profissional;
import org.acme.model.Usuario_habilidade;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class Habilidade_profissionalRepository {

        /*
        CREATE TABLE T_RHSTU_HABILIDADE_PROFISSIONAL(
id_habilidade_profissional INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
nv_habilidade_profissional CHAR(30) check(nv_habilidade_profissional='basico' OR nv_habilidade_profissional='intermediário' OR nv_habilidade_profissional='avançado') NOT NULL,
nv_importancia CHAR(30) check(nv_importancia='basico' OR nv_importancia='intermediário' OR nv_importancia='avançado') NOT NULL,
id_habilidade INTEGER NOT NULL,
id_carreira INTEGER NOT NULL,
CONSTRAINT F_T_RHSTU_HABILIDADE FOREIGN KEY(id_habilidade) REFERENCES T_RHSTU_HABILIDADE(id_habilidade),
CONSTRAINT T_RHSTU_CARREIRA_F FOREIGN KEY(id_carreira) REFERENCES T_RHSTU_CARREIRA(id_carreira)
);
*/
        @Inject
        DataSource dataSource;

        public void inserirH_P(Habilidade_profissionalDTO h_p) throws SQLException {
            String sql= "INSERT INTO T_RHSTU_HABILIDADE_PROFISSIONAL (nv_habilidade_profissional, nv_importancia, id_habilidade, id_carreira) VALUES (?, ?, ?,?)";
            try(Connection con= dataSource.getConnection();
                PreparedStatement ps= con.prepareStatement(sql)){
                ps.setString(1,h_p.getNivel_habilidade_profissional());
                ps.setString(2,h_p.getNv_importancia());
                ps.setInt(3,h_p.getId_habilidade());
                ps.setInt(4,h_p.getId_carreira());

                ps.executeUpdate();
            }catch (SQLException e){
                throw new SQLException(e);
            }

        }

        public List<Habilidade_profissional> RelatorioUsuarioH(int id)throws SQLException{
            List<Habilidade_profissional> l= new ArrayList<>();
            String sql ="SELECT * FROM T_RHSTU_HABILIDADE_PROFISSIONAL WHERE id_habilidade_profissional=?";
            try(Connection con= dataSource.getConnection();
                PreparedStatement ps= con.prepareStatement(sql)){

                ps.setInt(1,id);

                try(ResultSet rs = ps.executeQuery()){
                    while (rs.next()){
                        Habilidade_profissional u= new Habilidade_profissional();
                        u.setId_habilidade_profissional(rs.getInt(1));
                        u.setNivel_habilidade_profissional(rs.getString(2));
                        u.setNv_importancia(rs.getString(3));
                        u.setId_habilidade(rs.getInt(4));
                        u.setId_carreira(rs.getInt(5));

                        l.add(u);
                    }
                }
                return l;
            }catch (SQLException e){
                throw new SQLException(e);
            }
        }
        public void RemoverU_h(int id) throws SQLException {
            String sql = "DELETE FROM T_RHSTU_HABILIDADE_PROFISSIONAL WHERE id_habilidade_profissional=?";
            try (Connection con = dataSource.getConnection();
                 PreparedStatement ps = con.prepareStatement(sql))
            {
                ps.setInt(1, id);

                int deletado=ps.executeUpdate();

                if (deletado==0){
                    throw new SQLException("Nenhuma apagamento");
                }

            }catch (SQLException e) {
                throw new SQLException("Erro de remover");
            }
        }

    public void updante(int id, String nv_ha_p, String nv_i, int id_h, int id_carreira) throws SQLException {
        String sql= "UPDATE T_RHSTU_HABILIDADE_PROFISSIONAL" +
                " SET nv_habilidade_profissional=?, nv_importancia=?," +
                " id_habilidade=?, id_carreira=?" +
                " WHERE id_habilidade_profissional=?";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setString(1,nv_ha_p);
            ps.setString(2,nv_i);
            ps.setInt(3,id_h);
            ps.setInt(4,id_carreira);
            ps.setInt(5,id);

            int alterar=ps.executeUpdate();
            if (alterar>0){
                throw new IllegalArgumentException("Foi alterado");
            }
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    }

