package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.HabilidadeDTO;
import org.acme.model.Habilidade;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class HabilidadeRepository {
/*
CREATE TABLE T_RHSTU_HABILIDADE(
id_habilidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nm_habilidade VARCHAR(60) NOT NULL,
dm_mercado CHAR(30) check(dm_mercado='baixa' OR dm_mercado='media' OR dm_mercado='alta') NOT NULL,
nm_categoria VARCHAR(60) NOT NULL
);
*/
    @Inject
    DataSource dataSource;

    public void inserirHabilidade(HabilidadeDTO habilidadeDTO){
        String sql="INSERT INTO T_RHSTU_HABILIDADE(nm_habilidade, dm_mercado,nm_categoria) VALUES (?,?,?)";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps=con.prepareStatement(sql)){
            ps.setString(1,habilidadeDTO.getNm_habilidade());
            ps.setString(2,habilidadeDTO.getDm_mercado());
            ps.setString(3,habilidadeDTO.getNm_categoria());
            ps.executeUpdate();

        }catch (SQLException e){
            throw new RuntimeException("Erro de executar");
        }
    }

    public List<Habilidade> RelatorioHabilidade(String nome){
        String sql="SELECT * FROM T_RHSTU_HABILIDADE WHERE nm_habilidade=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setString(1,nome);

            List<Habilidade> l= new ArrayList<>();
            try(ResultSet rs= ps.executeQuery()) {
                while (rs.next()){
                    Habilidade habilidade= new Habilidade();
                    habilidade.setId_habilidade(rs.getInt(1));
                    habilidade.setNm_habilidade(rs.getString(2));
                    habilidade.setDm_mercado(rs.getString(3));
                    habilidade.setNm_categoria(rs.getString(4));

                    l.add(habilidade);
                }
                return l;
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }
    public void RemoverHabilidade(int id,String nome) {
        String sql = "DELETE FROM T_RHSTU_HABILIDADE WHERE id_habilidade=? AND nm_habilidade=?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1,id);
            ps.setString(2,nome);

            int deleta=ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Foi deletado");
            }
        }catch (SQLException e) {
            throw new RuntimeException("Erro de remover");
        }
    }

    public void updanteHabilidade(int id, String nm,String dm_m,String nm_c){
        String sql="UPDATE T_RHSTU_HABILIDADE SET nm_habilidade=?, dm_mercado=?, nm_categoria=? WHERE id_habilidade=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setString(1,nm);
            ps.setString(2,dm_m);
            ps.setString(3,nm_c);
            ps.setInt(4,id);
            int alteradas=ps.executeUpdate();
            if(alteradas>0){
                throw new SQLException("Foi atuliazando");
            }
        }catch (SQLException e){
            throw new RuntimeException("Erro: ",e);
        }
    }



}
