package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.Links_TrabalhoDTO;
import org.acme.model.Links_Trabalho;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class Links_trabalhoRepository {
    /*CREATE TABLE T_RHSTU_LINKS_TRABALHO(
    id_links INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    nm_empresa VARCHAR(60),
    nm_vaga VARCHAR(60),
    link_url VARCHAR(120) UNIQUE,
    id_carreira INTEGER,
    CONSTRAINT FK_T_RHSTU_CARREIRA FOREIGN KEY(id_carreira) REFERENCES T_RHSTU_CARREIRA(id_carreira)
);*/
    @Inject
    DataSource dataSource;

    public void inserirLink(Links_TrabalhoDTO li) throws SQLException {
        String sql="INSERT INTO T_RHSTU_LINKS_TRABALHO (nm_empresa, nm_vaga, link_url, id_carreira) VALUES (?, ?, ?, ?)";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {

            ps.setString(1,li.getNm_empresa());
            ps.setString(2,li.getNm_vaga());
            ps.setString(3,li.getLink_url());
            ps.setInt(4,li.getId_carreira());

            int inserido=ps.executeUpdate();
            if (inserido>0){
                throw new SQLException("Foi inserido");
            }

        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    public List<Links_Trabalho> RelatorioLinks(String nome) throws SQLException {
        String sql="SELECT * FROM T_RHSTU_LINKS_TRABALHO WHERE nm_vaga=?";
        List<Links_Trabalho> l= new ArrayList<>();
        try(Connection con = dataSource.getConnection();
        PreparedStatement ps = con.prepareStatement(sql)){
            ps.setString(1, nome);

            try(ResultSet rs= ps.executeQuery()) {
                while (rs.next()){
                    Links_Trabalho linksTrabalho= new Links_Trabalho();
                    linksTrabalho.setId_links(rs.getInt(1));
                    linksTrabalho.setNm_empresa(rs.getString(2));
                    linksTrabalho.setNm_vaga(rs.getString(3));
                    linksTrabalho.setLink_url(rs.getString(4));
                    linksTrabalho.setId_carreira(rs.getInt(5));

                    l.add(linksTrabalho);
                }
            }
            return l;
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    public void removerLink(String nm) throws SQLException {
        String sql="DELETE FROM T_RHSTU_LINKS_TRABALHO WHERE nm_vaga=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1,nm);
            int deleta= ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Foi deletado");
            }
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }
    public void updanteLink(int id_l, String nm_empresa, String nm_vaga, String link_url, int id_carreira) throws SQLException {
        String sql= "UPDATE T_RHSTU_LINKS_TRABALHO SET nm_empresa=?, nm_vaga=?, link_url=?, id_carreira=? WHERE id_links=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setString(1,nm_empresa);
            ps.setString(2,nm_vaga);
            ps.setString(3,link_url);
            ps.setInt(4,id_carreira);
            ps.setInt(5,id_l);

            int alterar=ps.executeUpdate();
            if (alterar==0){
                throw new SQLException("Nao foi atualizando");
            }
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

}
