package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.Teste_opcaoDTO;
import org.acme.model.Teste_opcao;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class Teste_opcaoRepository {

    /*
        CREATE TABLE T_RHSTU_TESTE_OPCAO(
            id_opcao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_questao INTEGER NOT NULL,
            id_carreira INTEGER not null,
            tx_opcao VARCHAR(100) NOT NULL,
            vl_opcao NUMBER not null,
            CONSTRAINT FK_T_RHSTU_TESTE_QUESTAO FOREIGN KEY(id_questao) REFERENCES T_RHSTU_TESTE_QUESTAO(id_questao),
            CONSTRAINT T_RHSTU_CARREIRA_FK FOREIGN KEY(id_carreira) REFERENCES T_RHSTU_CARREIRA(id_carreira)
            );
    */

    @Inject
    DataSource dataSource;

    public void inserirOpcao(Teste_opcaoDTO testeOpcao){

        String sql="INSERT INTO T_RHSTU_TESTE_OPCAO(id_questao, id_carreira, tx_opcao, vl_opcao) VALUES (?, ?, ?, ?)";
        try(Connection con= dataSource.getConnection(); PreparedStatement ps= con.prepareStatement(sql)){

            ps.setInt(1,testeOpcao.getId_questao());
            ps.setInt(2,testeOpcao.getId_carreira());
            ps.setString(3,testeOpcao.getTexto());
            ps.setInt(4,testeOpcao.getValor_escolha());

            ps.executeUpdate();
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }

    public List<Teste_opcao>relatorio(int id) throws SQLException{
        String sql="SELECT o.id_opcao, o.tx_opcao, o.vl_opcao, q.id_questao, c.id_carreira, FROM T_RHSTU_TESTE_OPCAO o, T_RHSTU_TESTE_QUESTAO q, T_RHSTU_CARREIRA c " +
                "WHERE o.id_opcao= q.id_questao AND o.id_carreira = c.id_carreira AND o.id_opcao=?";
        try(Connection con = dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1, id);
            List<Teste_opcao>l= new ArrayList<>();
            try(ResultSet rs= ps.executeQuery()){
                while (rs.next()){
                    Teste_opcao t= new Teste_opcao();
                    t.setId_opcao(rs.getInt(1));
                    t.setId_questao(rs.getInt(2));
                    t.setId_carreira(rs.getInt(3));
                    t.setTexto(rs.getString(4));
                    t.setValor_escolha(rs.getInt(5));

                    l.add(t);
                }
            }
            return l;
        } catch (SQLException e) {
            throw new SQLException(e);
        }
    }

    public  void RemoverOpcao(int id) throws SQLException{
        String sql= "DELETE FROM T_RHSTU_TESTE_OPCAO WHERE id_opcao=?";
        try(Connection con= dataSource.getConnection();PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1,id);
            int deleta= ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Foi deletando");
            }
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }

    public void updanteOpcao(int id_questao, int id_carreira, String tx, int vl, int id_opcao) throws SQLException{
        String sql="UPDATE T_RHSTU_TESTE_OPCAO SET id_questao=?, id_carreira=?, tx_opcao=?, vl_opcao=? WHERE id_opcao=?";

        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1,id_questao);
            ps.setInt(2,id_carreira);
            ps.setString(3,tx);
            ps.setInt(4,vl);
            ps.setInt(5,id_opcao);

            int alteradas= ps.executeUpdate();
            if(alteradas==0){
                throw new IllegalArgumentException("Não houver atuliazacao");
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }
}
