package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.Teste_QuestaoDTO;
import org.acme.model.Teste_Questao;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


/*
CREATE TABLE T_RHSTU_TESTE_QUESTAO(
id_questao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tx_questao VARCHAR(90) NOT NULL,
tipo_questao VARCHAR(60) NOT NULL
);
*/
@ApplicationScoped
public class Teste_questaoRepository {

    @Inject
    DataSource dataSource;

    public void inserirQuestao(Teste_QuestaoDTO testeQuestaoDTO){
        String sql="INSERT INTO T_RHSTU_TESTE_QUESTAO(tx_questao,tipo_questao) VALUES (?,?)";
        try(Connection con = dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql))
        {
            ps.setString(1,testeQuestaoDTO.getTexto_questao());
            ps.setString(2,testeQuestaoDTO.getTipo_questao());

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public List<Teste_Questao> relatorio(int id){
        String sql="select * from T_RHSTU_TESTE_QUESTAO where id_questao=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1,id);

            List<Teste_Questao> l= new ArrayList<>();

            try(ResultSet rs=ps.executeQuery()) {
                while (rs.next()){
                    Teste_Questao t= new Teste_Questao();
                    t.setId_questao(rs.getInt(1));
                    t.setTexto_questao(rs.getString(2));
                    t.setTipo_questao(rs.getString(3));

                    l.add(t);
                }
                return l;
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }
    public List<Teste_Questao> lista() throws SQLException{
        String sql="SELECT * FROM T_RHSTU_TESTE_QUESTAO ORDER BY id_questao";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {
            ResultSet rs=ps.executeQuery();
            List<Teste_Questao>listaQuestao= new ArrayList<>();

            while (rs.next()){
                Teste_Questao testeQuestao= new Teste_Questao();
                testeQuestao.setId_questao(rs.getInt(1));
                testeQuestao.setTexto_questao(rs.getString(2));
                testeQuestao.setTipo_questao(rs.getString(3));
                listaQuestao.add(testeQuestao);
            }
            return listaQuestao;
        }
    }

    public void RemoverQuestao(int id){
        String sql="DELETE FROM T_RHSTU_TESTE_QUESTAO WHERE id_questao=?";
        try(Connection con= dataSource.getConnection();
        PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1,id);

            int deleta= ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Foi deletado");
            }
        }catch (SQLException e){
            throw new RuntimeException("Erro em enviar");
        }

    }

    public  void updanteQuestao(int id, String tx, String tipo){
        String sql="UPDATE T_RHSTU_TESTE_QUESTAO SET tx_questao=?,tipo_questao=? WHERE id_questao=?";
        try(Connection con = dataSource.getConnection();
        PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setString(1,tx);
            ps.setInt(2,id);
            ps.setString(3, tipo);
        }catch (SQLException e){
            throw new RuntimeException("Erro de updante");
        }
    }

}
