package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.UsuarioDTO;
import org.acme.model.Usuario;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class UsuarioRepository {

    /*
    CREATE TABLE T_RHSTU_USUARIO(id_usuario NUMBER GENERATED BY ‘DEFAULT’ AS IDENTITY PRIMARY KEY,
    nm_usuario VARCHAR(80),
    idade NUMBER,
    email_usuario VARCHAR(100),
    senha_usuario VARCHAR(100))
    */

    @Inject
    DataSource dateSource;

    public void cadastrarUsuario(UsuarioDTO usuarioDTO){
        String sql= "INSERT INTO T_RHSTU_USUARIO (nm_usuario,cpf, idade, email_usuario, senha_usuario) VALUES (?,?,?,?,?)";
        try(Connection con = dateSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)
        ) {
            ps.setString(1,usuarioDTO.getNome());
            ps.setString(2,usuarioDTO.getCpf());
            ps.setInt(3, usuarioDTO.getIdade());
            ps.setString(4, usuarioDTO.getEmail());
            ps.setString(5,usuarioDTO.getSenha());

            ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    public boolean existeEmail(String email_usuario){
        String sql="SELECT COUNT(*) FROM T_RHSTU_USUARIO WHERE email_usuario=?";
        try(Connection con=dateSource.getConnection();
            PreparedStatement ps=con.prepareStatement(sql)) {
            ps.setString(1,email_usuario);
            try(ResultSet rs= ps.executeQuery()){
                return (rs.next() && rs.getInt(1)>0);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    public List<Usuario> login(String email, String senha){
        String sql="select * from T_RHSTU_USUARIO WHERE email_usuario=? AND senha_usuario=?";
        try(Connection con =dateSource.getConnection();
            PreparedStatement ps=con.prepareStatement(sql)){
            ps.setString(1,email);
            ps.setString(2,senha);
            List<Usuario>l= new ArrayList<>();
            try(ResultSet rs=ps.executeQuery()){
                while (rs.next()){
                    Usuario usuario= new Usuario();
                    usuario.setId_usuario(rs.getInt(1));
                    usuario.setNome(rs.getString(2));
                    usuario.setCpf(rs.getString(3));
                    usuario.setIdade(rs.getInt(4));
                    usuario.setEmail(rs.getString(5));
                    usuario.setSenha(rs.getString(6));

                    l.add(usuario);
                }
                return l;
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
    }
    public void DeletarConta(String email, String senha){
        String sql="DELETE FROM T_RHSTU_USUARIO WHERE email_usuario=? AND senha_usuario=?";

        try(Connection con = dateSource.getConnection();
        PreparedStatement ps=con.prepareStatement(sql)){
            ps.setString(1,email);
            ps.setString(2,senha);

            int deleta=ps.executeUpdate();
            if (deleta>0){
                throw new SQLException("Conta removida");
            }
        }catch (SQLException e){
            throw new RuntimeException("Erro de remover");
        }
    }
    public void updanteConta(Usuario usuario){
        String sql="UPDATE T_RHSTU_USUARIO SET nm_usuario=?,cpf=?, idade=?, email_usuario=?, senha_usuario=? WHERE id_usuario=? AND email_usuario=? AND senha_usuario=?";
        try(Connection con= dateSource.getConnection(); PreparedStatement ps=con.prepareStatement(sql)){

            ps.setString(2,usuario.getNome());
            ps.setString(3,usuario.getCpf());
            ps.setInt(4,usuario.getIdade());
            ps.setString(5,usuario.getEmail());
            ps.setString(6,usuario.getSenha());
            ps.setInt(7,usuario.getId_usuario());
            ps.setString(8,usuario.getEmail());
            ps.setString(9,usuario.getSenha());

            int alteracao=ps.executeUpdate();
            if (alteracao>0){
                throw new SQLException("Atualizando");
            }
        }catch (SQLException e){
            throw new RuntimeException("Erro de conectar");
        }
    }
}
