package org.acme.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.Usuario_habilidadeDTO;
import org.acme.model.Usuario_habilidade;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class Usuario_habilidadeRepository {

    /*
    CREATE TABLE T_RHSTU_USUARIO_HABILIDADE(
    id_habilidade_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    id_usuario INTEGER NOT NULL,
    id_habilidade INTEGER NOT NULL,
    lv_proficiencia CHAR(30) check(lv_proficiencia='basico' OR lv_proficiencia='intermediário' OR lv_proficiencia='avançado') not null,
    CONSTRAINT FK_T_RHSTU_HABILIDADE FOREIGN KEY(id_habilidade) REFERENCES T_RHSTU_HABILIDADE(id_habilidade),
    CONSTRAINT T_RHSTU_USUARIO_FK FOREIGN KEY(id_usuario) REFERENCES T_RHSTU_USUARIO(id_usuario)
);
*/
    @Inject
    DataSource dataSource;

    public void inserirU_H(Usuario_habilidadeDTO usuarioHabilidadeDTO) throws SQLException{
        String sql= "INSERT INTO T_RHSTU_USUARIO_HABILIDADE (id_usuario, id_habilidade, lv_proficiencia) VALUES (?, ?, ?)";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)){
            ps.setInt(1,usuarioHabilidadeDTO.getId_usuario());
            ps.setInt(2,usuarioHabilidadeDTO.getId_habilidade());
            ps.setString(3,usuarioHabilidadeDTO.getLv_proficiencia());

            ps.executeUpdate();
        }catch (SQLException e){
            throw new SQLException(e);
        }

    }

    public List<Usuario_habilidade> RelatorioUsuarioH(int id_habilidade_usuario)throws SQLException{
        List<Usuario_habilidade> l= new ArrayList<>();
        String sql ="SELECT * FROM T_RHSTU_USUARIO_HABILIDADE WHERE id_habilidade_usuario=?";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)){

            ps.setInt(1,id_habilidade_usuario);

            try(ResultSet rs = ps.executeQuery()){
                while (rs.next()){
                    Usuario_habilidade u= new Usuario_habilidade();
                    u.setId_habilidade_usuario(rs.getInt(1));
                    u.setId_usuario(rs.getInt(2));
                    u.setId_habilidade(rs.getInt(3));
                    u.setLv_proficiencia(rs.getString(4));

                    l.add(u);
                }
            }
            return l;
        }catch (SQLException e){
            throw new SQLException(e);
        }
    }
    public void RemoverU_h(int id) throws SQLException {
        String sql = "DELETE FROM T_RHSTU_USUARIO_HABILIDADE WHERE id_habilidade_usuario=?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql))
        {
            ps.setInt(1, id);

            int deletado=ps.executeUpdate();

            if (deletado==0){
                throw new SQLException("Não foi deletado");
            }

        }catch (SQLException e) {
            throw new SQLException("Erro de remover");
        }
    }

    public void updanteU_h(int id, int id_u, int id_h, String lv) throws SQLException{
        String sql="UPDATE T_RHSTU_USUARIO_HABILIDADE SET " +
                "id_usuario  = ?, " +
                "id_habilidade  = ?, " +
                "lv_proficiencia  = ? " +
                " WHERE id_habilidade_usuario = ?";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {
            ps.setInt(1, id_u);
            ps.setInt(2,id_h);
            ps.setString(3,lv);
            ps.setInt(4, id);


            int alteradas=ps.executeUpdate();
            if (alteradas==0){
                throw new IllegalArgumentException("Não houver atuliazacao");
            }

        }catch (SQLException e){
            throw new SQLException("Erro de executar updante.");
        }
    }

}
